name: Code quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        shell: bash
        run: flutter analyze | tee ./flutter_analyze_report.txt
      - name: Riverpod lint
        shell: bash
        run: dart run custom_lint | tee ./flutter_analyze_report.txt
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        if: always()
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Setup danger
        uses: MeilCli/danger-action@v5
        if: always()
        with:
          plugins_file: '.github/Gemfile'
          danger_file: '.github/Dangerfile'
          danger_id: 'danger-pr'
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
